install: true
script: "MAVEN_OPTS=\"-Xmx512m\" JAVA_OPTS=\"-Xmx512m\" mvn -T 1C --batch-mode clean post-integration-test"
language: java
os:
  - linux
jdk:
  - oraclejdk8
addons: # make sure we're using the latest Java as Travis default is quite old
  apt:
    packages:
      - oracle-java8-installer
