install: true
script: "mvn clean post-integration-test"
language: java
os:
  - linux
jdk:
  - oraclejdk8
addons: # make sure we're using the latest Java as Travis default is quite old
  apt:
    packages:
      - oracle-java8-installer
